stages:
  - test

# Job de test simple
test_job:
  stage: test
  before_script:
    - python --version
    - pip --version
    - pip install selenium webdriver_manager
  script:
    - echo "c'est good"
  only:
    - dev
    - main
  tags:
    - my-shell-runner
