stages:
  - test
  - deploy

# Job de test
test:
  stage: test
  before_script:
    - 'python --version'
    - 'pip --version'
    - 'pip install selenium'
  script:
    - 'python tests/test_harri_map.py'
  artifacts:
    paths:
      - screenshots/
  tags:
    - my-shell-runner

# Job de déploiement
deploy:
  stage: deploy
  script:
    - 'Write-Host "Déploiement en cours..."'
    # Commandes de déploiement ici
  environment:
    name: production
    url: https://votre-site.com
  only:
    - main
  tags:
    - my-shell-runner
