stages:
  - test
  - deploy

# Job de test pour la branche de développement
test_dev:
  stage: test
  before_script:
    - powershell -Command "python --version"
    - powershell -Command "pip --version"
    - powershell -Command "[System.Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';C:\Python39;C:\Python39\Scripts', [System.EnvironmentVariableTarget]::Process)"
    - powershell -Command "echo $env:PATH"
  script:
    - powershell -Command "pip install selenium webdriver_manager"
    - powershell -Command "python tests/test_harri_map.py"
  artifacts:
    paths:
      - screenshots/
  only:
    - dev
  tags:
    - shell-runner

# Job de test pour la branche principale
test_main:
  stage: test
  before_script:
    - "python --version"
    - powershell -Command "pip --version"
    - powershell -Command "[System.Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';C:\Python39;C:\Python39\Scripts', [System.EnvironmentVariableTarget]::Process)"
    - powershell -Command "echo $env:PATH"
  script:
    - powershell -Command "pip install selenium webdriver_manager"
    - powershell -Command "python tests/test_harri_map.py"
  artifacts:
    paths:
      - screenshots/
  only:
    - main
  tags:
    - shell-runner

# Job de déploiement
deploy:
  stage: deploy
  script:
    - powershell -Command "Write-Host 'Déploiement en cours...'"
    # Ajoutez ici vos commandes de déploiement spécifiques
  environment:
    name: production
    url: http://127.0.0.1:8000/
  only:
    - main
  tags:
    - shell-runner