stages:
  - test
  - deployement

# Job de test simple
test:
  stage: test
  script:
    - python --version
    - pip --version
    - Write-Host 'Les tests sont nickels
  tags:
    - my-shell-runner

deployement:
  stage: deployement
  script:
    - pwsh -Command "echo 'hello world'""
  tags:
    - my-shell-runner