stages:
  - test
  - deploy

# Job de test pour la branche de développement
test_dev:
  stage: test
  before_script:
    - powershell -Command "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser"
    - powershell -Command "pip install selenium"
    - powershell -Command "pip install webdriver_manager"
    - powershell -Command "Invoke-WebRequest -Uri 'https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_win32.zip' -OutFile 'chromedriver_win32.zip'"
    - powershell -Command "Expand-Archive -Path 'chromedriver_win32.zip' -DestinationPath 'C:\chromedriver'"
    - powershell -Command "[System.Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';C:\chromedriver', [System.EnvironmentVariableTarget]::Machine)"
  script:
    - powershell -Command "python tests/test_harri_map.py"
  artifacts:
    paths:
      - screenshots/
  only:
    - dev

# Job de test pour la branche principale
test_main:
  stage: test
  before_script:
    - powershell -Command "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser"
    - powershell -Command "pip install selenium"
    - powershell -Command "pip install webdriver_manager"
    - powershell -Command "Invoke-WebRequest -Uri 'https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_win32.zip' -OutFile 'chromedriver_win32.zip'"
    - powershell -Command "Expand-Archive -Path 'chromedriver_win32.zip' -DestinationPath 'C:\chromedriver'"
    - powershell -Command "[System.Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';C:\chromedriver', [System.EnvironmentVariableTarget]::Machine)"
  script:
    - powershell -Command "python tests/test_harri_map.py"
  artifacts:
    paths:
      - screenshots/
  only:
    - main

# Job de déploiement
deploy:
  stage: deploy
  script:
    - powershell -Command "Write-Host 'Déploiement en cours...'"
    # Ajoutez ici vos commandes de déploiement spécifiques
  environment:
    name: production
    url: http://127.0.0.1:8000/
  only:
    - main
