stages:
  - test
  - deploy

# Job de test pour la branche de développement
test_dev:
  stage: test
  script:
    - pip install selenium webdriver_manager
    - python tests/test_harri_map.py
  artifacts:
    paths:
      - screenshots/
  only:
    - dev
  tags:
    - my-shell-runner

# Job de test pour la branche principale
test_main:
  stage: test
  script:
    - pip install selenium webdriver_manager
    - python tests/test_harri_map.py
  artifacts:
    paths:
      - screenshots/
  only:
    - main
  tags:
    - my-shell-runner

# Job de déploiement
deploy:
  stage: deploy
  script:
    - echo "Déploiement en cours..."
    # Ajoute ici tes commandes de déploiement spécifiques
  environment:
    name: production
    url: http://127.0.0.1:8000/
  only:
    - main
  tags:
    - my-shell-runner
