stages:
  - test

# Job de test simple
test:
  stage: test
  before_script:
    - pwsh -Command "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser"
  script:
    - pwsh -Command "python --version"
    - pwsh -Command "pip --version"
    - pwsh -Command "Write-Host 'Les tests sont nickels'"
  tags:
    - my-shell-runner
