stages:
  - test

# Job de test simple
test_job:
  stage: test
  before_script:
    - pwsh -Command "python --version"
    - pwsh -Command "pip --version"
    - pwsh -Command "pip install selenium webdriver_manager"
  script:
    - pwsh -Command "python -c 'print(\"Running simple test...\")'"
  only:
    - dev
    - main
  tags:
    - my-shell-runner
